# stores all champ names, damage type, attributes
# key, name, type, attributes (ex. dmg type, tankiness, engage, cc, heal, shield, global, etc)

class ChampDB:

    def __init__(self, data={
        1: ["aatrox", 4, ["fighter", "tank"], "no mana", ["ad"]],
        2: ["ahri", 5, ["mage", "assassin"], "mana", ["ap"]],
        3: ["akali", 7, ["assassin"], "energy", ["ap"]],
        4: ["akshan", 0, ["marksman", "assassin"], "mana", ["ad"]],
        5: ["alistar", 7, ["tank", "support"], "mana", ["ap"]],
        6: ["amumu", 3, ["tank", "mage"], "mana", ["ap"]],
        7: ["anivia", 10, ["mage", "support"], "mana", ["ap"]],
        8: ["annie", 6, ["mage"], "mana", ["ap"]],
        9: ["aphelios", 10, ["marksman"], "mana", ["ad"]],
        10: ["ashe", 4, ["marksman", "support"], "mana", ["ad"]],
        11: ["aurelion sol", 7, ["mage"], "mana", ["ap"]],
        12: ["azir", 9, ["mage", "marksman"], "mana", ["ap"]],
        13: ["bard", 9, ["support", "mage"], "mana", ["ap"]],
        14: ["blitzcrank", 4, ["tank", "fighter"], "mana", ["ap"]],
        15: ["brand", 4, ["mage"], "mana", ["ap"]],
        16: ["braum", 3, ["support", "tank"], "mana", ["ap"]],
        17: ["caitlyn", 6, ["marksman"], "mana", ["ad"]],
        18: ["camille", 4, ["fighter", "tank"], "mana", ["ad"]],
        19: ["cassiopeia", 10, ["mage"], "mana", ["ap"]],
        20: ["cho'gath", 5, ["tank", "mage"], "mana", ["ap"]],
        21: ["corki", 6, ["marksman"], "mana", ["ad", "ap"]],
        22: ["darius", 2, ["fighter", "tank"], "mana", ["ad"]],
        23: ["diana", 4, ["fighter", "mage"], "mana", ["ap"]],
        24: ["draven", 8, ["marksman"], "mana", ["ad"]],
        25: ["dr. mundo", 5, ["fighter", "tank"], "no mana", ["ap"]],
        26: ["ekko", 8, ["assassin", "fighter"], "mana", ["ap"]],
        27: ["elise", 9, ["mage", "assassin"], "mana", ["ap"]],
        28: ["evelynn", 10, ["assassin", "mage"], "mana", ["ap"]],
        29: ["ezreal", 7, ["marksman", "mage"], "mana", ["ad"]],
        30: ["fiddlesticks", 9, ["mage", "support"], "mana", ["ap"]],
        31: ["fiora", 3, ["fighter", "assassin"], "mana", ["ad"]],
        32: ["fizz", 6, ["assassin", "fighter"], "mana", ["ap"]],
        33: ["galio", 5, ["tank", "mage"], "mana", ["ap"]],
        34: ["gangplank", 9, ["fighter"], "mana", ["ad"]],
        35: ["garen", 5, ["fighter", "tank"], "no mana", ["ad"]],
        36: ["gnar", 8, ["fighter", "tank"], "no mana", ["ad"]],
        37: ["gragas", 5, ["fighter", "mage"], "mana", ["ap"]],
        38: ["graves", 3, ["marksman"], "mana", ["ad"]],
        39: ["gwen", 5, ["fighter", "assassin"], "mana", ["ap"]],
        40: ["hecarim", 6, ["fighter", "tank"], "mana", ["ad"]],
        41: ["heimerdinger", 8, ["mage", "support"], "mana", ["ap"]],
        42: ["illaoi", 4, ["fighter", "tank"], "mana", ["ad"]],
        43: ["irelia", 5, ["fighter", "assassin"], "mana", ["ad"]],
        44: ["ivern", 7, ["support", "mage"], "mana", ["ap"]],
        45: ["janna", 7, ["support", "mage"], "mana", ["ap"]],
        46: ["jarvan iv", 5, ["tank", "fighter"], "mana", ["ad"]],
        47: ["jax", 5, ["fighter", "assassin"], "mana", ["ad"]],
        48: ["jayce", 7, ["fighter", "marksman"], "mana", ["ad"]],
        49: ["jhin", 6, ["marksman", "mage"], "mana", ["ad"]],
        50: ["jinx", 6, ["marksman"], "mana", ["ad"]],
        51: ["kai'sa", 6, ["marksman"], "mana", ["ad"]],
        52: ["kalista", 7, ["marksman"], "mana", ["ad"]],
        53: ["karma", 5, ["mage", "support"], "mana", ["ap"]],
        54: ["karthus", 7, ["mage"], "mana", ["ap"]],
        55: ["kassadin", 8, ["assassin", "mage"], "mana", ["ap"]],
        56: ["katarina", 8, ["assassin", "mage"], "no mana", ["ad", "ap"]],
        57: ["kayle", 7, ["fighter", "support"], "mana", ["ad", "ap"]],
        58: ["kayn", 8, ["fighter", "assassin"], "mana", ["ad"]],
        59: ["kennen", 4, ["mage", "marksman"], "energy", ["ap"]],
        60: ["kha'zix", 6, ["assassin"], "mana", ["ad"]],
        61: ["kindred", 4, ["marksman"], "mana", ["ad"]],
        62: ["kled", 7, ["fighter", "tank"], "no mana", ["ad"]],
        63: ["kog'maw", 6, ["marksman", "mage"], "mana", ["ad"]],
        64: ["leblanc", 9, ["assassin", "mage"], "mana", ["ap"]],
        65: ["lee sin", 6, ["fighter", "assassin"], "energy", ["ad"]],
        66: ["leona", 4, ["tank", "support"], "mana", ["ap"]],
        67: ["lillia", 8, ["fighter", "mage"], "mana", ["ap"]],
        68: ["lissandra", 6, ["mage"], "mana", ["ap"]],
        69: ["lucian", 6, ["marksman"], "mana", ["ad"]],
        70: ["lulu", 5, ["support", "mage"], "mana", ["ap"]],
        71: ["lux", 5, ["mage", "support"], "mana", ["ap"]],
        72: ["malphite", 2, ["tank", "fighter"], "mana", ["ap"]],
        73: ["malzahar", 6, ["mage", "assassin"], "mana", ["ap"]],
        74: ["maokai", 3, ["tank", "mage"], "mana", ["ap"]],
        75: ["master yi", 4, ["assassin", "fighter"], "mana", ["ad"]],
        76: ["miss fortune", 1, ["marksman"], "mana", ["ad"]],
        77: ["mordekaiser", 4, ["fighter"], "no mana", ["ap"]],
        78: ["morgana", 1, ["mage", "support"], "mana", ["ap"]],
        79: ["nami", 5, ["support", "mage"], "mana", ["ap"]],
        80: ["nasus", 6, ["fighter", "tank"], "mana", ["ad"]],
        81: ["nautilus", 6, ["tank", "fighter"], "mana", ["ap"]],
        82: ["neeko", 5, ["mage", "support"], "mana", ["ap"]],
        83: ["nidalee", 8, ["assassin", "mage"], "mana", ["ap"]],
        84: ["nocturne", 4, ["assassin", "fighter"], "mana", ["ad"]],
        85: ["nunu & willump", 4, ["tank", "fighter"], "mana", ["ap"]],
        86: ["nilah", 7, ["fighter", "assassin"], "mana", ["ad"]],
        87: ["olaf", 3, ["fighter", "tank"], "mana", ["ad"]],
        88: ["orianna", 7, ["mage", "support"], "mana", ["ap"]],
        89: ["ornn", 5, ["tank", "fighter"], "mana", ["ap"]],
        90: ["pantheon", 4, ["fighter", "assassin"], "mana", ["ad"]],
        91: ["poppy", 6, ["tank", "fighter"], "mana", ["ad"]],
        92: ["pyke", 7, ["support", "assassin"], "mana", ["ad"]],
        93: ["qiyana", 8, ["assassin", "fighter"], "mana", ["ad"]],
        94: ["quinn", 5, ["marksman", "assassin"], "mana", ["ad"]],
        95: ["rakan", 5, ["support", "mana"], ["ap"]],
        96: ["rammus", 5, ["tank", "fighter"], "mana", ["ap"]],
        97: ["rek'sai", 3, ["fighter"], "no mana", ["ad"]],
        98: ["rell", 0, ["tank"], "mana", ["ap"]],
        99: ["renata glasc", 8, ["support", "mage"], "mana", ["ap"]],
        100: ["renekton", 3, ["fighter", "tank"], "no mana", ["ad"]],
        101: ["rengar", 8, ["assassin", "fighter"], "no mana", ["ad"]],
        102: ["riven", 8, ["fighter", "assassin"], "no mana", ["ad"]],
        103: ["rumble", 10, ["fighter", "mage"], "no mana", ["ap"]],
        104: ["ryze", 7, ["mage", "fighter"], "mana", ["ap"]],
        105: ["samira", 6, ["marksman"], "mana", ["ad"]],
        106: ["sejuani", 4, ["tank", "fighter"], "mana", ["ap"]],
        107: ["senna", 7, ["marksman", "support"], "mana", ["ad"]],
        108: ["seraphine", 0, ["mage", "support"], "mana", ["ap"]],
        109: ["sett", 2, ["fighter", "tank"], "no mana", ["ad"]],
        110: ["shaco", 9, ["assassin"], "mana", ["ad", "ap"]],
        111: ["shen", 4, ["tank"], "no mana", ["ad"]],
        112: ["shyvana", 4, ["fighter", "tank"], "no mana", ["ap"]],
        113: ["singed", 5, ["tank", "fighter"], "mana", ["ap"]],
        114: ["sion", 5, ["tank", "fighter"], "mana", ["ad"]],
        115: ["sivir", 4, ["marksman"], "mana", ["ad"]],
        116: ["skarner", 5, ["fighter", "tank"], "mana", ["ap"]],
        117: ["sona", 4, ["support", "mage"], "mana", ["ap"]],
        118: ["soraka", 3, ["support", "mage"], "mana", ["ap"]],
        119: ["swain", 8, ["mage", "fighter"], "mana", ["ap"]],
        120: ["sylas", 5, ["mage", "assassin"], "mana", ["ap"]],
        121: ["syndra", 8, ["mage", "support"], "mana", ["ap"]],
        122: ["tahm kench", 5, ["support", "tank"], "mana", ["ap"]],
        123: ["taliyah", 5, ["mage", "support"], "mana", ["ap"]],
        124: ["talon", 7, ["assassin", "mana", "ad"]],
        125: ["taric", 3, ["support", "fighter"], "mana", ["ap"]],
        126: ["teemo", 6, ["marksman", "assassin"], "mana", ["ap"]],
        127: ["thresh", 7, ["support", "fighter"], "mana", ["ap"]],
        128: ["tristana", 4, ["marksman", "assassin"], "mana", ["ad"]],
        129: ["trundle", 5, ["fighter", "tank"], "mana", ["ad"]],
        130: ["tryndamere", 5, ["fighter", "assassin"], "no mana", ["ad"]],
        131: ["twisted fate", 9, ["mage"], "mana", ["ap"]],
        132: ["twitch", 6, ["marksman", "assassin"], "mana", ["ad"]],
        133: ["udyr", 7, ["fighter", "tank"], "mana", ["ad"]],
        134: ["urgot", 8, ["fighter", "tank"], "mana", ["ad"]],
        135: ["varus", 2, ["marksman", "mage"], "mana", ["ad"]],
        136: ["vayne", 8, ["marksman", "assassin"], "mana", ["ad", "true"]],
        137: ["veigar", 7, ["mage"], "mana", ["ap"]],
        138: ["vel'koz", 8, ["mage"], "mana", ["ap"]],
        139: ["vex", 0, ["mage"], "mana", ["ap"]],
        140: ["vi", 4, ["fighter", "assassin"], "mana", ["ad"]],
        141: ["viego", 5, ["assassin", "fighter"], "no mana", ["ad"]],
        142: ["viktor", 9, ["mage"], "mana", ["ap"]],
        143: ["vladimir", 7, ["mage"], "no mana", ["ap"]],
        144: ["volibear", 3, ["fighter", "tank"], "mana", ["ad", "ap"]],
        145: ["warwick", 3, ["fighter", "tank"], "mana", ["ad"]],
        146: ["wukong", 3, ["fighter", "tank"], "mana", ["ad"]],
        147: ["xayah", 5, ["marksman"], "mana", ["ad"]],
        148: ["xerath", 8, ["mage"], "mana", ["ap"]],
        149: ["xin zhao", 2, ["fighter", "assassin"], "mana", ["ad"]],
        150: ["yasuo", 10, ["fighter", "assassin"], "no mana", ["ad"]],
        151: ["yone", 8, ["assassin", "fighter"], "no mana", ["ad"]],
        152: ["yorick", 6, ["fighter", "tank"], "mana", ["ad"]],
        153: ["yuumi", 2, ["support", "mage"], "mana", ["ap"]],
        154: ["zac", 8, ["tank", "fighter"], "no mana", ["ap"]],
        155: ["zed", 7, ["assassin"], "energy", ["ad"]],
        156: ["zeri", 6, ["marksman"], "mana", ["ad"]],
        157: ["ziggs", 4, ["mage"], "mana", ["ap"]],
        158: ["zilean", 6, ["support", "mage"], "mana", ["ap"]],
        159: ["zoe", 5, ["mage", "support"], "mana", ["ap"]],
        160: ["zyra", 7, ["mage", "support"], "mana", ["ap"]]
    }):
        self.data = data

    def getChamps(self):
        return self.data
